# This is a basic workflow to help you get started with Actions

name: actualiza

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
    
  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:
  schedule:
  - cron: '40 11 * * *'
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "Fecha github:$(date)"
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          npm install epg-grabber
          npm install cheerio
          npm install @ntlab/sfetch
          npm install debug
          npm install luxon
          npx epg-grabber --config=sites/gatotv.com/gatotv.com.config.js --channels=sites/gatotv.com/gatotv.com.channels.xml --output=gatotv.com.xml --days=3 --timeout=30000
          npx epg-grabber --config=sites/superguidatv.it/superguidatv.it.config.js --channels=sites/superguidatv.it/superguidatv.it.channels.xml --output=superguidatv.it.xml --days=3 --timeout=30000
      - name: Dar permisos de ejecución al script
        run: |
          chmod +x .github/workflows/EPG_script.sh
      - name: Ejecutar script
        run: .github/workflows/EPG_script.sh
      - name: Commit & Push changes
        uses: actions-js/push@master
        #uses: stefanzweifel/git-auto-commit-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  
      



