# This is a basic workflow to help you get started with Actions

name: actualiza

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
    
  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:
  schedule:
  - cron: '0 7-23/6 * * *'
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo hola
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          npm install epg-grabber
          npm install cheerio
          npx epg-grabber --config=sites/superguidatv.it/superguidatv.it.config.js --channels=sites/superguidatv.it/superguidatv.it.channels.xml --output=superguidatv.it.xml --days=3 --timeout=30000
          npx epg-grabber --config=sites/nos.pt/nos.pt.config.js --channels=sites/nos.pt/nos.pt.channels.xml --output=nos.pt.xml --days=3 --timeout=30000
          npx epg-grabber --config=sites/sky.de/sky.de.config.js --channels=sites/sky.de/sky.de.channels.xml --output=sky.de.xml --days=3 --timeout=30000
          #npx epg-grabber --config=sites/bt.com/bt.com.config.js --channels=sites/bt.com/bt.com.channels.xml --output=bt.com.xml --days=3 --timeout=30000
          npx epg-grabber --config=sites/player.ee.co.uk/player.ee.co.uk.config.js --channels=sites/player.ee.co.uk/player.ee.co.uk.channels.xml --output=bt.com.xml --days=3 --timeout=30000
          #npx epg-grabber --config=sites/tvguide.com/tvguide.com.config.js --channels=sites/tvguide.com/tvguide.com.channels.xml --output=tvguide.com.xml --days=3 --timeout=30000
          #npx epg-grabber --config=sites/directv.com/directv.com.config.js --channels=sites/directv.com/directv.com.channels.xml --output=directv.com.xml --days=3 --timeout=30000
          npx epg-grabber --config=sites/flixed.io/flixed.io.config.js --channels=sites/flixed.io/flixed.io.channels.xml --output=flixed.io.xml --days=3 --timeout=30000
          npx epg-grabber --config=sites/programtv.onet.pl/programtv.onet.pl.config.js --channels=sites/programtv.onet.pl/programtv.onet.pl.channels.xml --output=programtv.onet.pl.xml --days=3 --timeout=30000
          npx epg-grabber --config=sites/guidatv.sky.it/guidatv.sky.it.config.js --channels=sites/guidatv.sky.it/guidatv.sky.it.channels.xml --output=guidatv.sky.it.xml --days=3 --timeout=30000
          #npx epg-grabber --config=sites/tvtv.us/tvtv.us.config.js --channels=sites/tvtv.us/tvtv.us.channels.xml --output=beinsports.com.xml --days=3 --timeout=30000
          #npx epg-grabber --config=sites/beinsports.com/beinsports.com.config.js --channels=sites/beinsports.com/beinsports.com_us-en.channels.xml --output=beinsports.com.xml --days=3 --timeout=30000
          npx epg-grabber --config=sites/ziggogo.tv/ziggogo.tv.config.js --channels=sites/ziggogo.tv/ziggogo.tv.channels.xml --output=ziggogo.tv.xml --days=3 --timeout=30000
          npx epg-grabber --config=sites/programetv.ro/programetv.ro.config.js --channels=sites/programetv.ro/programetv.ro.channels.xml --output=programetv.ro.xml --days=3 --timeout=30000
          npx epg-grabber --config=sites/cablego.com.pe/cablego.com.pe.config.js --channels=sites/cablego.com.pe/cablego.com.pe.channels.xml --output=cablego.com.pe.xml --days=3 --timeout=30000
          npx epg-grabber --config=sites/mi.tv/mi.tv.config.js --channels=sites/mi.tv/mi.tv_ar.channels.xml --output=mi.tv.xml --days=3 --timeout=30000
      - name: Commit & Push changes
        uses: actions-js/push@master
        #uses: stefanzweifel/git-auto-commit-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  
      



