# This is a basic workflow to help you get started with Actions

name: script_epg(manual)

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      # Runs a single command using the runners shell
      - name: Dar permisos de ejecución al script
        run: |
          chmod +x .github/workflows/EPG_script.sh
      - name: Ejecutar script
        run: .github/workflows/EPG_script.sh
      - name: Commit & Push changes
        uses: actions-js/push@master
        #uses: stefanzweifel/git-auto-commit-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  
      


